# .github/workflows/cd.yml
name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        run: sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Node.js dependencies
        run: |
          npm install
          npm run build

      - name: Package application
        run: zip -r build.zip .

      - name: Upload build to S3
        run: aws s3 cp build.zip s3://my-app-bucket/build.zip

      - name: Deploy to EC2
        run: |
          ssh -i /path/to/my-key.pem ec2-user@<EC2_INSTANCE_IP> "aws s3 cp s3://my-app-bucket/build.zip /app && unzip -o /app/build.zip -d /app && pm2 restart app"
