name: Deploy Lambda Layer

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy-layer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Create Layer
      run: |
        # Create the nodejs directory structure
        mkdir -p nodejs
        
        # Create a minimal package.json with only necessary dependencies
        node -e "
          const pkg = require('./package.json');
          const newPkg = {
            type: 'module',
            dependencies: {
              'adm-zip': pkg.dependencies['adm-zip'],
              'dotenv': pkg.dependencies['dotenv'],
              'fs-extra': pkg.dependencies['fs-extra'],
              'semver': pkg.dependencies['semver']
            }
          };
          require('fs').writeFileSync('nodejs/package.json', JSON.stringify(newPkg, null, 2));
        "
        
        # Install only the minimal dependencies
        cd nodejs
        npm install --production
        
        # Remove unnecessary files
        
        # Create the layer zip
        zip -r layer.zip nodejs

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy Layer
      run: |
        aws lambda publish-layer-version \
          --layer-name common-dependencies \
          --description "Common dependencies for Lambda functions" \
          --zip-file fileb://layer.zip \
          --compatible-runtimes nodejs20.x

