name: Deploy Lambda Layer

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy-layer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Create Layer
      run: |
        # Start fresh
        rm -rf nodejs layer.zip
        mkdir -p nodejs
        
        # Create a minimal package.json with only required dependencies from main package.json
        node -e "
          const pkg = require('./package.json');
          const newPkg = {
            type: 'module',
            dependencies: {
              'adm-zip': pkg.dependencies['adm-zip'],
              'semver': pkg.dependencies['semver']
            }
          };
          console.log('Creating layer package.json with these dependencies:', newPkg.dependencies);
          require('fs').writeFileSync('nodejs/package.json', JSON.stringify(newPkg, null, 2));
        "
        
        # Show what we're including
        echo "\nLayer package.json contents:"
        cat nodejs/package.json
        
        # Install only the specified dependencies
        cd nodejs
        npm install --omit=dev
        
        # Debug sizes
        echo "\nSize of node_modules:"
        du -sh node_modules/*
        
        # Create minimal zip
        cd ..
        zip -r layer.zip nodejs
        
        # Show final zip size
        ls -lh layer.zip

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy Layer
      run: |
        aws lambda publish-layer-version \
          --layer-name common-dependencies \
          --description "Common dependencies for Lambda functions" \
          --zip-file fileb://layer.zip \
          --compatible-runtimes nodejs20.x

