name: CI/CD for lambda function

on:
  push:
    branches:
      - 'feature/getAllPackages'
      - main
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
    
    #- name: Lint
    #  run: npm run lint
    
    # - name: Test
    #   run: npm run test:single

    - name: Rename uploadPackage handler file
      run: mv dist/handlers/uploadPackageLambdaHandler.js dist/handlers/uploadPackageLambdaHandler.mjs
    
    - name: Rename resetHandler file
      run: mv dist/handlers/resetLambdaHandler.js dist/handlers/resetLambdaHandler.mjs

    - name: Rename getPackageHandler file
      run: mv dist/handlers/getPackageLambdaHandler.js dist/handlers/getPackageLambdaHandler.mjs

    - name: Rename getRatingHandler file
      run: mv dist/handlers/getRatingLambdaHandler.js dist/handlers/getRatingLambdaHandler.mjs

    - name: Rename searchPackagesHandler file
      run: mv dist/handlers/searchPackagesHandler.js dist/handlers/searchPackagesHandler.mjs

    - name: Rename getSomePackagesHandler file
      run: mv dist/handlers/getSomePackagesHandler.js dist/handlers/getSomePackagesHandler.mjs

    - name: Rename updatePackageHandler file
      run: mv dist/handlers/updatePackageLambdaHandler.js dist/handlers/updatePackageLambdaHandler.mjs

    - name: Prepare for deployment
      run: npm prune --production

    - name: Create deployment package
      run: |
        cd dist
        zip -r ../function.zip .
        cd ..
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - name: Deploy lambda function
      run: |
        aws lambda update-function-code --function-name arn:aws:lambda:us-east-2:412381743875:function:uploadPackage --zip-file fileb://function.zip
        aws lambda update-function-code --function-name arn:aws:lambda:us-east-2:412381743875:function:reset --zip-file fileb://function.zip
        aws lambda update-function-code --function-name arn:aws:lambda:us-east-2:412381743875:function:getPackage --zip-file fileb://function.zip
        aws lambda update-function-code --function-name arn:aws:lambda:us-east-2:412381743875:function:getRating --zip-file fileb://function.zip
        aws lambda update-function-code --function-name arn:aws:lambda:us-east-2:412381743875:function:searchPackages --zip-file fileb://function.zip
        aws lambda update-function-code --function-name arn:aws:lambda:us-east-2:412381743875:function:updatePackage --zip-file fileb://function.zip
        aws lambda update-function-code --function-name arn:aws:lambda:us-east-2:412381743875:function:getSomePackages --zip-file fileb://function.zip
